evbeda/suppliers_management

- .gitignore
- supplier_management_site/settings/base.py
- users_app/tests.py
- users_app/validate_ap_user.py
Only allow eventbrite accounts to login using google oauth
> [MAJOR] Validate email in google oauth

- supplier_management_site/settings/production.py
Fixing setting configuration in production.py that was overriding a middleware used for i18n
> [PATCH ] EDA-532 i18n

- AP_app/__init__.py
- AP_app/tests.py
- AP_app/urls.py
- AP_app/views.py
- invoices_app/models.py
- invoices_app/tests.py
- supplier_management_site/settings/base.py
- supplier_management_site/settings/dev.py
- supplier_management_site/settings/production.py
- templates/AP_app/ap-home.html
- templates/AP_app/invoice-list.html
- users_app/tests.py
Added view for AP invoice list, with permissions.
> [Major] [EDA-564] AP invoice list

- AP_app/tests.py
- supplier_app/tests.py
- supplier_app/urls.py
- supplier_app/views.py
- templates/supplier_app/invoice-list.html
List view for supplier invoices, filtered by tax payer.
> [Minor] [EDA-563] Added view for supplier invoices

- AP_app/views.py
- requirements.txt
- static/css/global.css
- supplier_app/forms.py
- supplier_app/views.py
- supplier_management_site/settings/base.py
- templates/AP_app/invoice-list.html
- templates/_pagination.html
- templates/supplier_app/invoice-list.html
Edited css styles to follow eb colors
> Added pagination to invoices list

- supplier_app/__init__.py
- supplier_app/tests.py
- supplier_app/urls.py
- supplier_app/views.py
- templates/AP_app/ap-taxpayers.html
When AP go into his/her home, is able to see all new suppliers with status equal to PENDING. Also they can see suppliers who have changed some information, in this case the suppliers' status is CHANGE REQUIRED
> [MAJOR] EDA-549, EDA-546. List all new suppliers in Ap home

- invoices_app/__init__.py
- invoices_app/tests.py
- invoices_app/views.py
- templates/supplier_app/invoice-list.html
Added permissions in order that an invoice can only be edited by the AP or the supplier if it's in CHANGES REQUEST status
> [Patch] Added permissions to the update view.

- invoices_app/tests.py
Test validation for pdf extension and size on invoice form.
> [MINOR] Added test for Invoice form pdf validation

- invoices_app/forms.py
- invoices_app/views.py
Deleted duplicated pdf extension validation and also validated get methods to return a 404 error in case the object is not found.
> [Minor] [fix] Deleted duplicated file size validation.

- supplier_app/models.py
- supplier_app/tests.py
- supplier_app/tests_company.py
- supplier_app/urls.py
- supplier_app/views.py
- templates/supplier_app/company_creation.html
- templates/supplier_app/company_selector.html
- users_app/tests.py
-implemented company required restriction
-implemented company assigment for first time login
-implemented company creation and asigment for first time login
> [MINOR] EDA-583 View for a user without company

- supplier_app/forms.py
- supplier_app/models.py
- supplier_app/tests_company.py
- templates/supplier_app/company_creation.html
- templates/supplier_app/company_selector.html
- templates/supplier_app/taxpayer-creation.html
added str for company model in order to get the name for dropdown in template
added company selector template using the str as dropdown
added company creator template to create company for supplier
> [MINOR] Template for user without company

- invoices_app/forms.py
- invoices_app/views.py
- templates/supplier_app/invoices_form.html
Now the validation for a duplicated invoice renders the error in the template.
> [patch] Fixed error when creating a duplicated invoice

- supplier_app/tests/test_view.py
- templates/AP_app/ap-taxpayer-details.html
- templates/AP_app/ap-taxpayers.html
- templates/AP_app/navbar.html
- templates/supplier_app/supplier-home.html
Jira tickets : EDA-622
The AP must see all the certification loaded by the supplier
> Show pdf files on the taxpayer detail template

- supplier_app/tests/test_view.py
- templates/registration/login.html
When a user log in and the url has the 'next' uri param then the page redirects him to the 'next' url
> [EDA-643]Bug fixed

- supplier_app/tests/test_view.py
- supplier_app/views.py
Integration test for user joining a company
> minor refactor and added some test for email invitation

- invoices_app/__init__.py
- invoices_app/filters.py
- invoices_app/models.py
- invoices_app/tests/test_base.py
- invoices_app/tests/test_detail_invoice.py
- invoices_app/tests/test_invoice.py
- invoices_app/tests/test_permissions.py
- invoices_app/views.py
- users_app/decorators.py
- users_app/migrations/0002_group_permissions.py
- users_app/mixins.py
- users_app/models.py
Views now require certain permissions in order to access them.
Changed initial permissions creation in the permissions migration.
> [EDA-528] Configured permissions for users in views

- supplier_app/__init__.py
- supplier_app/models.py
- supplier_app/tests/test_model.py
- supplier_app/tests/test_view.py
- supplier_app/views.py
- supplier_management_site/settings/base.py
- supplier_management_site/tests/test.py
- templates/mail_template.html
- utils/exceptions.py
- utils/send_email.py
Implemented existing email template for compnay invitation and taxpayer status change
Refactored approve, deny methods and send_invitation to use taxpayer_notification and compnay_invitation_notification
> [MINOR] EDA-664 Create template for email notifications

- invoices_app/admin.py
- invoices_app/factory_boy.py
- invoices_app/filters.py
- invoices_app/forms.py
- invoices_app/models.py
- invoices_app/urls.py
- invoices_app/views.py
- supplier_app/__init__.py
- supplier_app/admin.py
- supplier_app/filters.py
- supplier_app/forms.py
- supplier_app/models.py
- supplier_app/tests/__init__.py
- supplier_app/tests/test_forms.py
- supplier_app/tests/test_view.py
- supplier_app/urls.py
- supplier_app/views.py
- templates/AP_app/ap-taxpayers.html
- templates/messages_notification.html
- templates/supplier_app/company_list.html
- templates/supplier_app/navbar.html
- templates/supplier_app/supplier-home.html
- templates/supplier_app/taxpayer-creation.html
When a functionality is executed there must be a success message or an error message
> [EDA-599] Display notification messages

- invoices_app/__init__.py
- invoices_app/filters.py
- invoices_app/tests/test_invoice.py
- invoices_app/tests/test_permissions.py
- invoices_app/views.py
- templates/AP_app/admins-list.html
- templates/AP_app/navbar.html
- users_app/__init__.py
- users_app/decorators.py
- users_app/migrations/0002_group_permissions.py
- users_app/mixins.py
- users_app/models.py
- users_app/tests/test_user.py
- users_app/urls.py
- users_app/views.py
Created a view to list all the users with an Eventbrite email and allows the AP manager to assign/remove permissions groups to users.
> [EDA-587] Permissions assignment for admins

- supplier_app/tests/test_forms.py
- supplier_app/tests/test_view.py
- supplier_app/views.py
- supplier_management_site/settings/dev.py
- users_app/migrations/0002_group_permissions.py
- users_app/mixins.py
- users_app/tests/test_user.py
If an user wants to access (using the url) to a page which he doesn't have permissions, he can't.
> [MAJOR] EDA-603 Implement permissions for suppliers

- supplier_app/__init__.py
- supplier_app/custom_messages.py
- supplier_app/tests/test_view.py
- supplier_app/urls.py
- supplier_app/views.py
- supplier_management_site/settings/base.py
- templates/mail_template.html
- templates/messages_notification.html
CompanySelectorView removed, now when a supplier click on the link and login he is automatically related with the company
> [EDA-689] Remove join company step

- supplier_app/tests/test_view.py
- supplier_app/views.py
- users_app/migrations/0002_group_permissions.py
- users_app/tests/test_user.py
Used mixing to restrict access to ap_views based on required permissions
> Add ap permission

- invoices_app/filters.py
- invoices_app/forms.py
- invoices_app/views.py
- supplier_app/filters.py
- utils/custom_filters.py
- utils/send_email.py
Now the date pickers are displayed in the selected language and with the correct date format.
> Fixed datepicker not being translated

- supplier_app/change_status_strategy.py
- supplier_app/fixtures/EB_entities_fixture.json
- supplier_app/models.py
- supplier_app/tests/test_view.py
- supplier_app/urls.py
- supplier_app/views.py
- templates/AP_app/ap-taxpayer-details.html
- templates/comments.html
- users_app/models.py
Supplier can edit taxpayer information but the status changes to pending
Ap can require change in taxpayer the status changes to change required
> Request change taxpayer

- invoices_app/tests/test_permissions.py
- supplier_app/__init__.py
- supplier_app/tests/test_view.py
- supplier_management_site/settings/base.py
- supplier_management_site/settings/production.py
- templates/AP_app/admin_create.html
- templates/AP_app/admins-list.html
- templates/navbar.html
- users_app/__init__.py
- users_app/forms.py
- users_app/migrations/0002_group_permissions.py
- users_app/models.py
- users_app/pipeline/pipeline.py
- users_app/tests/test_permissions.py
- users_app/tests/test_user.py
- users_app/urls.py
- users_app/views.py
- utils/send_email.py
Allow AP managers to create others AP admins and managers
> [MAJOR]Create admins

- templates/invoices_app/invoice_filters.html
- templates/navbar.html
- templates/registration/admin_create.html
- templates/registration/admins-list.html
- templates/supplier_app/AP/company_creation.html
Button cancel added to company creation and AP creation
Icon search in company list view
> Feature ui fixes

- users_app/migrations/0002_group_permissions.py
- users_app/models.py
- users_app/pipeline/pipeline.py
- users_app/tests/test_permissions.py
Resolve login to everyone and add a new role
> Login as Buyer

- static/js/taxpayer_creation.js
- templates/supplier_app/Supplier/bank-info-arg.html
- templates/supplier_app/Supplier/bank-info-usa.html
- templates/supplier_app/Supplier/taxpayer-creation.html
Added new bank form inputs on taxpayer creation form
> Completed bank form on front end

- templates/supplier_app/Supplier/bank-info-arg.html
- templates/supplier_app/Supplier/taxpayer-creation.html
As a supplier, I want to choose the payment type
> adding field in html

- supplier_app/migrations/0001_initial.py
- supplier_app/models.py
> char allow 50 characters

- supplier_app/migrations/0015_auto_20191111_2040.py
- supplier_app/migrations/0016_auto_20191113_1702.py
- supplier_app/models.py
> Fixing Bug when two taxpayer in the same supplier

- supplier_management_site/auth/eventbrite_custom.py
> fixinfg auth bug in eb login

- utils/send_email.py
When the company have a new user, we have to work with that user information
> modifing query for new user on supplier

- templates/supplier_app/taxpayer-details.html
Adding support to new tab in PDF﻿
> Adding new tab in pdf view

- invoices_app/change_status_strategy.py
- invoices_app/tests/test_invoice.py
- templates/invoices_app/invoice_detail.html
We need put an only workday id in the invoice, in the first state, so when we add in progress state we also add an extra field to workday id, and we have a twice field what do the same.
I deleted the field in approve state, and keep the field in "In Progress" field ﻿
> EDA-1053 Change form in approve state

- supplier_app/change_status_strategy.py
- users_app/models.py
As took with Nico Caif I add come changes
> adding comment reviews

- templates/invoices_app/invoice_detail.html
Currently, Paid status does not support comments.
> send coments on a piad invoice

- static/js/pdf_validation.js
We added a suport to PDF files, with capital case, for this, I added a new line accepted the files terminated in PDF in capital﻿
> Adding Suport to PDF files

- static/css/spinner.css
- static/js/taxpayer_creation.js
- static/js/taxpayer_creation_form_logic.js
- templates/supplier_app/Supplier/taxpayer-creation.html
The taxpayer creation form didn't have a nice way of showing the supplier that the form was uploading correctly.
I added a spinner that shows up when the form is submitted and the validation is ok.
> EDA-1103 Added spinner after submitting form

- templates/supplier_app/supplier-home.html
Added Eventbrite Entity to table to better differentiate taxpayer in case of having many.
> EDA-1138 Added eventbrite entity to table

- supplier_app/tests/test_view.py
- supplier_app/views.py
- templates/supplier_app/AP/company_creation.html
due to security breach in the create company form, the team decided that the buyer have to send only one invitation in the create company form
> adding invitation company on create company

- supplier_app/new_urls/AP_urls.py
- supplier_app/tests/test_view.py
- templates/navbar.html
Changing the home for buyers from the company list to taxpayers+company list
> Refactor for buyers home

- templates/navbar.html
AP have to see old companies list for send invitations
> redirecting nav

- supplier_app/forms.py
- supplier_app/tests/test_view.py
- supplier_app/views.py
EDA-1195: https://jira.evbhome.com/browse/EDA-1195
----
> EDA-1195: Not remembering EB Entity to bill when editing Taxpayer Information

- templates/invoices_app/invoices_form.html
EDA-1192: https://jira.evbhome.com/browse/EDA-1192
-----
Remove the files from the template, the user is not modified for future uses.
----
> EDA-1192: Remove fields from invoice form

- supplier_app/forms.py
I add an field in exclude form﻿
> Adding exclude field

- templates/supplier_app/taxpayer-details.html
Taxpayer details view was improved to fit information better.
> improved taxpayer details template

- supplier_management_site/locale/es/LC_MESSAGES/django.po
- supplier_management_site/locale/pt_BR/LC_MESSAGES/django.po
- templates/invoices_app/invoice-list.html
- templates/invoices_app/invoice_detail.html
https://jira.evbhome.com/browse/EDA-1203
-----
As an AP Administrator, I want to know that EB entity was billed when looking at an invoice
See attachments for both situations.
Acceptance criteria:
New column exists on Invoices table for the AP user.
EB entity to bill is displayed on the Invoice detail view.  (Details section)
> EDA-1203: Insert EB entity on invoices
